import enum


class UserRole(str, enum.Enum):
    SUPERADMIN = "SUPERADMIN"
    STREAM_MANAGER = "STREAM_MANAGER"
    OPERATOR = "OPERATOR"


class AuditActionType(str, enum.Enum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    USER_CREATE = "USER_CREATE"
    USER_UPDATE = "USER_UPDATE"
    USER_DELETE = "USER_DELETE"
    STREAM_CREATE = "STREAM_CREATE"
    STREAM_UPDATE = "STREAM_UPDATE"
    STREAM_DELETE = "STREAM_DELETE"
    STREAM_LOCK = "STREAM_LOCK"
    STREAM_UNLOCK = "STREAM_UNLOCK"
    BROADCAST_START = "BROADCAST_START"
    BROADCAST_STOP = "BROADCAST_STOP"
    MENTION_CREATE = "MENTION_CREATE"
    MENTION_UPDATE = "MENTION_UPDATE"
